# Generated by Django 5.2.8 on 2025-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AddField(
            model_name='customer',
            name='test_field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
